In [1]:
from datetime import date, datetime, timedelta
import pandas as pd
import os.path

# load in roster
roster = pd.read_csv('../data/Roster.csv',
    header = 0)
names = roster['Full Name'].tolist()
roster['Attendance Score'] = 0

In [2]:
# note the date the csv is most recently updated on
roster['Last Updated'] = str(datetime.now())

In [3]:
# update attendance
#note that attendance.csv pull and attendance_clean must have already been done
attendance = pd.read_csv('../data/Attendance_Cleaned.csv',header = 0)
for name in names:
    score = attendance.mean(axis=1).loc[attendance['Name']==name].values[0]
    roster['Attendance Score'].loc[roster['Full Name']==name] = int(score*100)

C:\Users\RT185116\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\core\indexing.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [4]:
# update absent
absent = pd.read_csv('../data/Absence.csv',
                     header = 0, #header is in first line
                     parse_dates = [0,2,3],
                     infer_datetime_format = True)
# clean Timestamp to just a Date
absent['Timestamp'] = absent['Timestamp'].apply(lambda x: x.date())
absent['Start Date'] = absent['Start Date'].apply(lambda x: x.date())
absent['Last Date'] = absent['Last Date'].apply(lambda x: x.date())

tomorrow = date.today() + timedelta(days=1)
# filter to see who will be absent tomorrow and mark them as such
absentPpl = absent['Name'].loc[absent['Start Date'] <= tomorrow].loc[absent['Last Date'] >= tomorrow].values
for name in absentPpl:
    roster['Status'].loc[roster['Full Name']==name] = 'Absent'

In [8]:
# update injured
injured = pd.read_csv('../data/Injury_Report.csv',
                     header = 0, #header is in first line
                     parse_dates = [0],
                     infer_datetime_format = True)
# clean Timestamp to just a Date
injured['Timestamp'] = injured['Timestamp'].apply(lambda x: x.date())

# filter to see who will be absent tomorrow and mark them as such
injured['Last Date'] = injured.apply(lambda x: x['Timestamp'] + timedelta(days=int(x['(Additional) Days off required'])), axis=1)

injuredPpl = injured['Name'].loc[injured['Last Date'] >= tomorrow].values
for name in injuredPpl:
    roster['Status'].loc[roster['Full Name']==name] = 'Injured'

In [ ]:
# save updated roster
roster.to_csv('../data/Roster.csv', index=False)

In [10]:
roster

,Full Name,Goes By,Type,Status,Attendance Score,Last Updated
0,Name0,Allison,Starboard,Ok,83,2017-03-16 15:33:18.665000
1,Name1,AnneBlair,Starboard,Injured,66,2017-03-16 15:33:18.665000
2,Name2,Beth,Port,Ok,66,2017-03-16 15:33:18.665000
3,Name 2,Courtney,Port,Injured,100,2017-03-16 15:33:18.665000
4,Name3,Heyerdahl,Starboard,Absent,100,2017-03-16 15:33:18.665000
5,Name4,Murray,Port,Ol,83,2017-03-16 15:33:18.665000
6,Name5,Jo,BiPort,Ok,83,2017-03-16 15:33:18.665000
7,Name6,Kaela,Starboard,Injured,100,2017-03-16 15:33:18.665000
8,Name7,Kate,Starboard,Ok,100,2017-03-16 15:33:18.665000
9,Name8,Kat,BiStar,Ok,100,2017-03-16 15:33:18.665000
10,Name9,Kelly,Port,Ok,100,2017-03-16 15:33:18.665000
11,Name10,Lulu,Port,Ok,100,2017-03-16 15:33:18.665000
12,Name11,Mandy,Port,Ok,100,2017-03-16 15:33:18.665000
13,Name12,Melanie,Port,Injured,100,2017-03-16 15:33:18.665000
14,Name13,Boutom,Starboard,Ok,100,2017-03-16 15:33:18.665000
15,Name14,Stacks,Port,Ok,100,2017-03-16 15:33:18.665000
16,Name15,Renee,BiPort,Ok,100,2017-03-16 15:33:18.665000
17,Name16,Tera,Port,Ok,100,2017-03-16 15:33:18.665000
18,Name17,Blaine,Cox,Absent,100,2017-03-16 15:33:18.665000
19,Name18,Sarah,Cox,Ok,100,2017-03-16 15:33:18.665000
20,Name19,Steph,Cox,Ok,100,2017-03-16 15:33:18.665000